esphome:
  name: petlibro-plaf101
  friendly_name: Petlibro PLAF101

esp8266:
  board: nodemcuv2

logger:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

api:
  encryption:
    # Change Key to any random string
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

button:
  - platform: template
    name: "Feed"
    icon: "mdi:cat"
    on_press:
      - logger.log: "Button pressed"

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor