esphome:
  name: petlibro-plaf101
  friendly_name: Petlibro PLAF101
  on_boot:
    - priority: -100
      then:
        - switch.turn_off: motor_driver_in_b
        # - binary_sensor.template.publish:
        #     id: physical_motor_endstop
        #     state: OFF

esp8266:
  board: nodemcuv2

logger:

web_server:
  port: 80
  auth:
    username: !secret petlibro_plaf101_web_server_username
    password: !secret petlibro_plaf101_web_server_password

ota:
  - platform: esphome
    id: my_ota
    password: !secret petlibro_plaf101_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  min_auth_mode: WPA2
  ap:
    password: !secret petlibro_plaf101_wifi_ap_password

captive_portal:

api:
  encryption:
    key: !secret petlibro_plaf101_api_key
  reboot_timeout: 0s

button:
  - platform: template
    id: feed_once
    name: "Feed one scoop"
    icon: "mdi:cat"
    on_press:
      - logger.log:
          format: "feed_once on_press. Calling script script_feed."
          level: DEBUG
      - script.execute: script_feed

binary_sensor:
  # Physical buttons on the front
  - platform: gpio
    name: "REC_button (GPIO0)"
    id: physical_rec_button
    pin:
      number: GPIO00
      mode:
        input: true
        pullup: false
    filters:
      - invert:
      - delayed_on_off: 25ms

  - platform: gpio
    name: "FEED_button (GPIO4)"
    id: physical_feed_button
    pin:
      number: GPIO04
      mode:
        input: true
        pullup: false
    filters:
      - invert:
      - delayed_on_off: 25ms
    on_press:
      - script.execute: script_feed

  - platform: gpio
    name: "SET_button (GPIO13)"
    id: physical_set_button
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: false
    filters:
      - invert:
      - delayed_on_off: 25ms

  # Endstop on motor axle, detects 60deg rotation increments
  - platform: gpio
    name: "M_DET (GPIO12)"
    id: physical_motor_endstop
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
    filters:
      - invert:
    on_release:
      then:
        # Stop the motor.
        - switch.turn_off: motor_driver_in_b
        # - binary_sensor.template.publish:
        #     id: is_motor_running
        #     state: OFF

  # - platform: template
  #   id: is_motor_running
  #   on_press:
  #     then:
  #       - switch.turn_on: motor_driver_in_b
  #
  #   on_release:
  #     then:
  #       - switch.turn_off: motor_driver_in_b

sensor:
  - id: uptime_sensor
    platform: uptime
    type: seconds
    name: Uptime Sensor

  - id: rssi_sensor
    platform: wifi_signal
    update_interval: 30s

switch:
  - id: led2_blue
    platform: gpio
    pin:
      number: GPIO14
      mode: output
    inverted: true
    restore_mode: ALWAYS_OFF

  - id: led1_red
    platform: gpio
    pin:
      number: GPIO16
      mode: output
    inverted: true
    restore_mode: ALWAYS_OFF

  # We only need the motor to spin in one direction, so
  # grounding in_a while driving in_b high should be enough.
  # pin 3 (in_b) straight to GPIO5
  - id: motor_driver_in_b
    name: motor
    platform: gpio
    pin:
      number: GPIO5
      mode: output
    restore_mode: ALWAYS_OFF
    disabled_by_default: true # Controls frontend presence

status_led:
  pin:
    number: GPIO2
    inverted: True

script:
  - id: script_feed
    mode: queued # More presses will accumulate
    max_runs: 5
    then:
      - logger.log:
          format: "script_feed script begin."
          level: DEBUG

      - switch.turn_on: motor_driver_in_b
      # - binary_sensor.template.publish:
      #     id: is_motor_running
      #     state: ON

      # Do nothing until the position switch turns off the motor.
      - wait_until:
          condition:
            - switch.is_off: motor_driver_in_b

      - logger.log:
          format: "script_feed script complete."
          level: DEBUG

  - id: flash_wifi_error
    mode: restart
    then:
      - while:
          condition:
            lambda: |-
              return true;
          then:
            - switch.turn_on: led1_red
            - delay: 500ms
            - switch.turn_off: led1_red
            - delay: 500ms

interval:
  - interval: 2s
    then:
      - if:
          condition:
            wifi.connected:
          then:
            - script.stop: flash_wifi_error
            - if:
                condition:
                  switch.is_off: led1_red
                then:
                  - switch.turn_on: led1_red
          else:
            - script.execute: flash_wifi_error

  - interval: 1s
    then:
      - logger.log:
          format: "physical_motor_endstop=%d, motor_driver_in_b=%d"
          args:
            - "id(physical_motor_endstop).state"
            - "id(motor_driver_in_b).state"
