esphome:
  name: petlibro-plaf101
  friendly_name: Petlibro PLAF101

esp8266:
  board: nodemcuv2

logger:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

button:
  - platform: template
    name: "Feed"
    icon: "mdi:cat"
    on_press:
      - logger.log: "Button pressed"

binary_sensor:
  - platform: gpio
    pin: GPIO0
    name: "REC_KEY (GPIO0)"

  # - platform: gpio
  #   pin: GPIO1
  #   name: "GPIO1"

  # - platform: gpio
  #   pin: GPIO2
  #   name: "GPIO2"
  
  # - platform: gpio
  #   pin: GPIO3
  #   name: "GPIO3"

  - platform: gpio
    pin: GPIO04
    name: "FEED_KEY (GPIO4)"

  # - platform: gpio
  #   pin: GPIO5
  #   name: "GPIO5"

  # - platform: gpio
  #   pin: GPIO6
  #   name: "Not usable - Flash Clock (GPIO6)"

  # - platform: gpio
  #   pin: GPIO7
  #   name: "Not usable - Flash Data 0 (GPIO7)"

  # - platform: gpio
  #   pin: GPIO8
  #   name: "Not usable - Flash Data 1 (GPIO8)"

  # - platform: gpio
  #   pin: GPIO9
  #   name: "GPIO9"

  # - platform: gpio
  #   pin: GPIO10
  #   name: "GPIO10"

  # - platform: gpio
  #   pin: GPIO11
  #   name: "Not usable - Flash Command (GPIO11)"

  # - platform: gpio
  #   pin: GPIO12
  #   name: "GPIO12"

  - platform: gpio
    pin: GPIO13
    name: "SET_KEY (GPIO13)"

  # - platform: gpio
  #   pin: GPIO14
  #   name: "GPIO14"

  # - platform: gpio
  #   pin: GPIO15
  #   name: "GPIO15"

  # - platform: gpio
  #   pin: GPIO16
  #   name: "GPIO16"

  # - platform: gpio
  #   pin: GPIO07
  #   name: "Not usable - Flash Data 0 (GPIO7)"


sensor:
  - platform: uptime
    type: seconds
    name: Uptime Sensor

output:
  - platform: gpio
    pin:
      number: GPIO02
      mode: output
    id: led_on_board
    inverted: true

  - platform: gpio
    pin:
      number: GPIO14
      mode: output
    id: led2_blue
    inverted: true

  - platform: gpio
    pin:
      number: GPIO16
      mode: output
    id: led1_red
    inverted: true
