name: Status

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  validate_config:
    name: Validate ESPHome configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - name: Validate ESPHome config
        run: esphome config petlibro-plaf101.yaml
